# Site
repository: MigCaSan/portfolio
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Miguel Camacho
title: Machine Learning & Research Engineer
email: micasan4@teleco.upv.es
website: github.com/MigCaSan

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: MigCaSan
linkedin_username: miguel-camacho-sánchez-37b8a520b
# Añade otros si quieres, ej. twitter, stackoverflow

# Additional icon links
additional_links:
- title: My Portfolio
  icon: fas fa-globe
  url: https://migcasan.github.io/

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a machine learning researcher with a strong interest in applying AI to scientific and engineering challenges.  

  At the CVBLab at Universitat Politècnica de València, I work on both academic and industry-oriented research, contributing to European projects. My experience covers areas like **Deep Learning, reinforcement learning, computer vision and physics-informed models**.  

  I also develop practical tools and open-source projects, from medical image segmentation to control models. Having built a solid research background, I am now eager to apply these skills to real-world problems and innovative applications.  

  Core technical expertise: <mark>Python</mark>, <mark>Deep Learning</mark>, <mark>Reinforcement Learning</mark>, <mark>Computer Vision</mark>, and <mark>Quantum ML</mark>.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: CVBLab – UPV Institute of Research and Innovation in Bioengineering
        sub_title: AI Researcher
        caption: Sep 2023 – Present
        quote: >
          Leading technical work and managing European research projects.
        description: |
          - Technical management of EU-funded projects METAMORPHA and TURBO, coordinating with research teams and industry partners.
          - Applied reinforcement learning and computer vision in multidisciplinary contexts.  
          - Development of AI solutions in real-world international frameworks.

      - layout: left
        title: CVBLab – UPV Institute of Research and Innovation in Bioengineering
        sub_title: Research Intern
        caption: Feb 2022 – Jul 2023
        quote: >
          Researching Quantum Machine Learning, Reinforcement Learning, and Computer Vision.
        description: |
          - Conducted research in **Quantum Machine Learning** with PennyLane.  
          - Developed reinforcement learning models applied to complex problem-solving.  
          - Designed and implemented deep learning models for signal and image analysis.  
          - Gained experience in Python, MATLAB, TensorFlow, and PyTorch.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Universitat Politècnica de València
        caption: 2022 – 2024
        sub_title: MSc in Telecommunication Engineering
        description: |
          Specialised in advanced communications, signal processing, and AI applications.

      - layout: left
        title: Universitat Politècnica de València
        caption: 2018 – 2022
        sub_title: BSc in Telecommunication Technologies and Services Engineering
        description: |
          Solid foundation in telecommunications, programming and applied engineering.

      - layout: left
        title: Stanford Online (Coursera)
        caption: 2022
        sub_title: Machine Learning
        link: https://coursera.org/verify/NYG3D742FEUL
        description: |
          Completed the foundational Stanford ML course by Andrew Ng.

      - layout: left
        title: Universitat Politècnica de València
        caption: Jul 2021
        sub_title: Deep Learning Applied to Signal and Image Analysis
        description: |
          Intensive course on deep learning methods applied to real datasets.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: METAMORPHA (EU Project)
        link: https://cordis.europa.eu/project/id/101057457
        quote: >
          European project on advanced photogrammetry and point cloud processing.
        description: |
          Participation as Research Engineer at CVBLab. Focused on dataset creation, AI-driven reconstruction, and point cloud analysis.

      - layout: top-middle
        title: TURBO (EU Project)
        link: https://cordis.europa.eu/project/id/101058054
        quote: >
          European project tackling industrial challenges with AI solutions.
        description: |
          Developed and managed AI modules in reinforcement learning and computer vision. Coordinated with industry partners for applied research.
          and managed AI modules in reinforcement learning and computer vision. Coordinated with industry partners for applied research.
      
      - layout: top-middle
        title: Physics-Informed Machine Learning
        link: https://github.com/MigCaSan/NewML
        additional_links:
          - title: MigCaSan/NewML
            icon: fab fa-github
            url: https://github.com/MigCaSan/NewML
        quote: >
          Combining physical models with machine learning to build more robust and explainable AI.
        description: |
          Research experiments in **Physics-Informed Neural Networks (PINNs)** applied to engineering and signal processing.  
          Focus on bridging data-driven learning with physical constraints for improved generalization and interpretability.
      

      - layout: top-middle
        title: AR Climbing Topo
        link: https://github.com/MigCaSan/AR_Climbing_Topo
        additional_links:
          - title: MigCaSan/AR_Climbing_Topo
            icon: fab fa-github
            url: https://github.com/MigCaSan/AR_Climbing_Topo
        quote: >
          Augmented reality topo-mapping tool for climbers.
        description: |
          Developed an AR-based application for mapping climbing routes,
          overlaying topographic and route information via camera view.  
          Explores geospatial data processing, computer vision techniques,
          and interactive user interface elements for outdoor use.

      - layout: top-middle
        title: Segmentation for Prostate MRI
        link: https://github.com/MigCaSan/MRI_Prostate
        additional_links:
          - title: MigCaSan/MRI_Prostate
            icon: fab fa-github
            url: https://github.com/MigCaSan/MRI_Prostate
        quote: >
          Segmentation and clasification model for MRI of prostate
        description: |

      - layout: top-middle
        title: Recomender System
        link: https://github.com/MigCaSan/Recomender
        additional_links:
          - title: MigCaSan/Recomender
            icon: fab fa-github
            url: https://github.com/MigCaSan/Recomender
        quote: >
          Recomender system application for estandaruze climbing grades
        description: 



  - title: Publications & Awards
    layout: list
    content:
      - layout: left
        title: Research Publications
        description: |
          - *Reinforcement learning for synchronised flow control in a  dual-gate resin infusion system*, 45th Risø International Symposium on Materials Science, 2025.  
          - *Towards Sustainable Precision: Machine Learning for Laser Micromachining Optimization*, IDEAL, 2024.    
      
      - layout: left
        title: Best Paper Award
        caption: IDEAL 2024
        description: |
          *Towards Sustainable Precision: Machine Learning for Laser Micromachining Optimization*  
          Awarded **Best Paper** at the International Conference on Intelligent Data Engineering and Automated Learning (IDEAL), 2024.




  - title: Skills
    layout: text
    content: |
      - **Programming:** Python, Java, C, MATLAB, JavaScript, HTML, CSS  
      - **Machine Learning:** Deep Learning (PyTorch, TensorFlow), Reinforcement Learning, Computer Vision, NLP, Quantum ML  
      - **Tools & Platforms:** Docker, Git, Linux, Jupyter, Web Scraping  
      - **Languages:** Spanish (Native), English (B2)

  - title: A Little More About Me
    layout: text
    content: |
      Outside of research and coding, I am passionate about:  
      - Mountain sports & climbing  
      - Outdoor adventures   

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
